theme = "duckquill"

title = "Agustín Ramiro Díaz"
base_url = "https://agustinramirodiaz.github.io/"
description = "Programmer and Acrobat"

compile_sass = true
minify_html = true
generate_feed = true
feed_filenames = ["atom.xml"]
build_search_index = false

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"

smart_punctuation = true
external_links_target_blank = true

[extra]
# Sets theme and browser theme color,
# see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
primary_color = "#ff7800"
# Same as primary_color, but with 20% opacity
primary_color_alpha = "rgba(255, 120, 0, 0.2)"
# Emoji favicon; can be set per-page or even section.
emoji_favicon = false
# If the favicon is GIF or not
animated_favicon = false
# Tera date format (not used in comments!),
# see https://docs.rs/chrono/0.4.31/chrono/format/strftime/index.html
# for all available variables.
date_format = "%d %B %Y"
# URL to issue tracker
issues_url = "https://github.com/AgustinRamiroDiaz/AgustinRamiroDiaz.github.io/issues"
# URL to website's source code
source_url = "https://github.com/AgustinRamiroDiaz/AgustinRamiroDiaz.github.io"
# Additional stylesheets; expects it to be in the ./static/ directory.
# If you are using Sass it will be compiled there anyway.
# stylesheets = [
#   "YOUR_STYLE.css",
#   "ALSO_YOUR_STYLE.css"
# ]

[extra.nav]
# Display Atom/RSS feed button in the nav
show_feed = true
# Links used in the nav
links = [
  # {url = "https://codeberg.org/daudix/duckquill", name = "Repo"},
  #  {url = "$BASE_URL/demo", name = "Demo"},
  { url = "$BASE_URL/blog", name = "Blog" },
  { url = "https://github.com/AgustinRamiroDiaz", name = "GitHub" },
  { url = "https://www.linkedin.com/in/agust%C3%ADn-ramiro-d%C3%ADaz-bb0387184/", name = "LinkedIn" },
  { url = "mailto:agustin.ramiro.diaz@gmail.com", name = "Contact" },
]

[extra.footer]
# URL to the website without the https:// part, used for Johnvertisement leaderboard
johnvert_ref = "daudix.codeberg.page"
# "© Title, YEAR" in the footer
show_copyright = false
# Johnvertisement in the footer
show_johnvert = false
# "Powered by Zola and Duckquill" in footer
show_powered_by = false
# Link to website source
show_source = false

# Based on https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/
#
# Mastodon-powered commenting.
# Values can be overridden in front-matter, e.g.
# for multi-author blogs or guest posts.
#
# These variables are also used for Mastodon verification,
# the needed rel="me" link is set in the head based on these.
[extra.comments]
# Your Mastodon API host; this should be where you have an account
host = "mstdn.social"
# Used to determine who the original poster is
user = "agustinramirodiaz"
